### ISSUE TITLE
Process events through the ScriptRuntime once instead of multiple times for every resource

### ISSUE THREAD

**Issue by 7Hazard** [altmp/cpp-sdk#13]
Every kind of event gets triggered for every resource, for no good reason other than "the resource might *want* to handle the event", which leads to duplicative processing (eg. deserialization) of the event when it can be done once if managed from the ScriptRuntime's point of view.

A smarter and more efficient method would be to have ScriptRuntime handle the event. The ScriptHandler would keep track of all event subscriptions in a hash table of handlers and trigger all the handlers for the event in question, once rather that multiple times.

This would also strengthen the reason and possibility of cancelling triggered events.

**Comment by vadzz-dev** [comment]
It never causes double deserialization if resourxe has no handlers

**Comment by 7Hazard** [comment]
Theres the option to subscribe to events through one handler via ICore::SubscribeEvent. Can be used to only process event data once rather than for every resource (CEvent::Type::ALL).
