### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Kalcor1337** [altmp/cpp-sdk#19]
If you move an Array into itself (let's say by a pointer), there will be a memory leak.

[Place](https://github.com/altmp/cpp-sdk/blob/d52d98b8a239499c6caef85cd637fbebe1a23814/types/Array.h#L73)

You need to add a check.
`if (this != &that)`

For copying, too, would not hurt.

**Comment by FabianTerhorst** [comment]
Can you provide a sample where it would leak.

**Comment by Kalcor1337** [comment]
Learn the basics.

```
Array<int> a;

Array<int>* one = &a; // Somehow
Array<int>* two = &a; // Somehow

*one = std::move(*two); // Leak
```

**Comment by LeonMrBonnie** [comment]
Stop being so rude here
