### ISSUE TITLE
Move instead of copy.

### ISSUE THREAD

**Issue by Kalcor1337** [altmp/cpp-sdk#20]
[Place](https://github.com/altmp/cpp-sdk/blob/d52d98b8a239499c6caef85cd637fbebe1a23814/types/Array.h#L128)

There will be a deep copying of the object, and here just moving it is enough. Change to:
`newData[i] = std::move(data[i]);`

**Comment by FabianTerhorst** [comment]
Can you describe why this is needed.

**Comment by Kalcor1337** [comment]
You won't believe it, but moving an object is much faster and more efficient than copying it. Can you imagine? Shock.

**Comment by FabianTerhorst** [comment]
Thats depending on the type of the array.

**Comment by FabianTerhorst** [comment]
Doesn't that makes the data invalid when its setted to the array and then invalidated inside the resize method but also used outside the array.

**Comment by Kalcor1337** [comment]
The memory you move from is deleted in the next line. Accordingly, you need to MOVE from it, not copy it.

**Comment by FabianTerhorst** [comment]
The next line only deletes the arrays, but doesn't the elements inside it.

**Comment by Kalcor1337** [comment]
Learn the basics.
