### ISSUE TITLE
Add to SDK.h new files

### ISSUE THREAD

**Issue by Kalcor1337** [altmp/cpp-sdk#22]
I think the SDK.h is missing these headers:

`#include <events/CFireEvent.h>
#include <events/CStartProjectileEvent.h>
#include <events/CPlayerWeaponChangeEvent.h>
#include <events/CVehicleAttachEvent.h>
#include <events/CVehicleDetachEvent.h>
#include <events/CNetOwnerChangeEvent.h>
#include <events/CPlayerEnteringVehicleEvent.h>`

Maybe there are some more. But it seems like everything.

**Comment by FabianTerhorst** [comment]
Feel free to do a pull request.

**Comment by Kalcor1337** [comment]
I look like a person who has a lot of extra time to sit on this garbage dump file and change something? I reported the problem, and you can do what you want with it.

**Comment by drakeee** [comment]
It took you much more time to register a new account, open an issue, argue about the whole thing on Discord as well rather than just do a PR, so basically yeah you have much free time
