### ISSUE TITLE
Getters at IVehicle

### ISSUE THREAD

**Issue by Kalcor1337** [altmp/cpp-sdk#28]
Don't you think that the getters in IVehicle should add the `const` qualifier? And in general, all interfaces seem to need to add `noexcept`.

**Comment by LeonMrBonnie** [comment]
I agree about the part with the `const` qualifier, if someone has some free time they could add them.
Unsure about the `noexcept` tho

**Comment by martonp96** [comment]
Hi Maxim @Kalcor1337,
Please open a pull request instead of creating issues.

**Comment by FabianTerhorst** [comment]
Got fixed in #39
