### ISSUE TITLE
IColshape::IsEntityIdIn doesn't make sense anymore

### ISSUE THREAD

**Issue by lackos888** [altmp/cpp-sdk#92]
I just noticed that some of our old scripts were using IColshape::IsEntityIdIn through JavaScript module, and it got broken. I realized that the definition for the function is maybe wrong / outdated, because there can be entities sharing same id but having a different type.

At latest release version JS module still supports IColshape::IsEntityIdIn, but it doesn't work anymore, IsEntityIn still works.

The CPP-SDK code i'm talking about: https://github.com/altmp/cpp-sdk/blob/a8a6d032e7cc75d4ec8b3896e771391d05797c87/script-objects/IColShape.h#L32

Support inside Javascript module: https://github.com/altmp/altv-js-module/blob/5ddb005d367c09795c3c61a1523d85c7a1758911/shared/bindings/ColShape.cpp#L7

**Comment by LeonMrBonnie** [comment]
Have you tried passing the remoteID to it?

**Comment by FabianTerhorst** [comment]
its syncId not script id.

**Comment by lackos888** [comment]
I used it on serverside btw, so there is no remoteID there @LeonMrBonnie
